"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { Boxes, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { createBag, deleteBag, updateBag } from "@/app/inventario/actions";
import { Button, Card } from "@/components/ui";
import type { BagWithComponents } from "@/lib/inventory-types";

export default function BagsView({ bags }: { bags: BagWithComponents[] }) {
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<BagWithComponents | null | undefined>(undefined); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const visible = useMemo(() => bags.filter((bag) => `${bag.nombre} ${bag.descripcion ?? ""} ${bag.ubicacion ?? ""}`.toLowerCase().includes(search.toLowerCase())), [bags, search]);
  const submit = (formData: FormData) => startTransition(async () => { const result = await (editing ? updateBag(formData) : createBag(formData)); if (result.ok) { setMessage(editing ? "Bolsa actualizada." : "Bolsa creada."); setEditing(undefined); } else setMessage(result.message); });
  const remove = (bag: BagWithComponents) => { if (!window.confirm(`¿Eliminar "${bag.nombre}"? Los componentes quedarán sin bolsa.`)) return; startTransition(async () => { const data = new FormData(); data.append("id", String(bag.id)); const result = await deleteBag(data); setMessage(result.ok ? "Bolsa eliminada." : result.message); }); };
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Bolsas</h1><p className="text-slate-500">Contenedores y ubicación del inventario.</p></div><Button onClick={() => setEditing(null)}><Plus size={18} className="mr-2 inline"/>Nueva bolsa</Button></div>
    {message && <div role="status" className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
    {editing !== undefined && <Card className="p-6"><h2 className="text-xl font-semibold">{editing ? "Editar bolsa" : "Nueva bolsa"}</h2><form action={submit} className="mt-4 grid gap-4 md:grid-cols-2">{editing && <input type="hidden" name="id" value={editing.id}/>}<label className="text-sm font-medium">Nombre<input required name="nombre" defaultValue={editing?.nombre} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-medium">Ubicación<input name="ubicacion" defaultValue={editing?.ubicacion ?? ""} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-medium md:col-span-2">Descripción<textarea name="descripcion" defaultValue={editing?.descripcion ?? ""} rows={3} className="mt-1 w-full rounded-xl border p-3"/></label><div className="flex gap-3 md:col-span-2"><Button disabled={pending} type="submit">{pending ? "Guardando..." : "Guardar bolsa"}</Button><Button type="button" variant="secondary" onClick={() => setEditing(undefined)}>Cancelar</Button></div></form></Card>}
    <div className="relative"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input aria-label="Buscar bolsas" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nombre, descripción o ubicación" className="w-full rounded-xl border bg-white py-3 pl-10 pr-4"/></div>
    <p className="text-sm text-slate-500">{visible.length} bolsas encontradas</p><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((bag) => <Card key={bag.id} className="p-5"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><Boxes className="text-blue-600"/><h2 className="font-semibold">{bag.nombre}</h2></div><p className="mt-2 text-sm text-slate-500">{bag.descripcion || "Sin descripción"}</p></div><div className="flex h-fit gap-1"><button aria-label={`Editar ${bag.nombre}`} onClick={() => setEditing(bag)} className="rounded-lg p-2 text-blue-600 hover:bg-blue-50"><Pencil size={17}/></button><button aria-label={`Eliminar ${bag.nombre}`} disabled={pending} onClick={() => remove(bag)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div></div><div className="mt-5 flex items-center justify-between text-sm"><span>{bag.ubicacion || "Sin ubicación"}</span><Link href={`/inventario?bag=${bag.id}`} className="font-medium text-blue-600 hover:underline">{bag.components.length} componentes</Link></div><p className="mt-3 text-xs text-slate-400">Actualizada {bag.updatedAt.toLocaleDateString("es-CO")}</p></Card>)}</div>{!visible.length && <Card className="p-12 text-center"><Boxes className="mx-auto text-slate-300" size={42}/><p className="mt-3 text-slate-500">No hay bolsas para mostrar.</p></Card>}</div>;
}
